name: Deploy Jupyter Notebook Presentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write


    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"

      - name: Install Required Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          pip install --force-reinstall -v mistune==2.0.4

      - name: Convert Jupyter Notebook to Presentation
        run: |
          jupyter nbconvert --to slides --output-dir=slides GFS_Physik.ipynb
          tree slides
      
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: slides/

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.3