name: Deploy Jupyter Notebook Presentation

on:
  push:
    branches:
      - main

jobs:
  deploy-presentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Required Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert

    - name: Convert Jupyter Notebook to Presentation
      run: |
        jupyter nbconvert --to slides --output-dir=slides GFS_Physik.ipynb

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: slides

    - name: Confirm Deployment
      run: echo "Presentation deployed to GitHub Pages."
